---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Пользователь должен иметь возможность просматривать название, рейтинг, цену со скидкой и без нее на странице товара и в каталоге
  - Пользователь должен иметь возможность продолжать выбирать товары в каталоге после добавления товара в корзину
  - Пользователь должен иметь возможность удалять товар из корзины со страницы корзины
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Корзина должна храниться в сессии браузера
implicit:
  - Валюта товара должна соответствовать выбранному языку
  - Скидка должна быть целым числом
  - При смене языка весь интерфейс, включая описание товара, переводится на выбранный язык
  - При открытии страницы товара есть возможность вернуться в каталог товаров
